// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agreements": {
            "get": {
                "description": "Возвращает список договоров с пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agreements"
                ],
                "summary": "Получить список договоров",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Количество записей на странице",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/agreement.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/agreement.AgreementResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/agreement.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новый договор между заказчиком и подрядчиком",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agreements"
                ],
                "summary": "Создать договор",
                "parameters": [
                    {
                        "description": "Данные договора",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/agreement.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Договор создан",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/agreement.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/agreement.AgreementResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    }
                }
            }
        },
        "/agreements/{id}": {
            "get": {
                "description": "Возвращает информацию о договоре",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agreements"
                ],
                "summary": "Получить договор по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID договора",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/agreement.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/agreement.AgreementResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Договор не найден",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет данные существующего договора",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agreements"
                ],
                "summary": "Обновить договор",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID договора",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/agreement.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/agreement.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/agreement.AgreementResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    },
                    "404": {
                        "description": "Договор не найден",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет договор по ID",
                "tags": [
                    "agreements"
                ],
                "summary": "Удалить договор",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID договора",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешное удаление"
                    },
                    "404": {
                        "description": "Договор не найден",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    }
                }
            }
        },
        "/equipment": {
            "get": {
                "description": "Возвращает список оборудования с пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Получить список оборудования",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Количество записей на странице",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/equipment.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/equipment.EquipmentResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/equipment.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новую единицу оборудования",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Создать оборудование",
                "parameters": [
                    {
                        "description": "Данные оборудования",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/equipment.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Оборудование создано",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/equipment.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/equipment.EquipmentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    }
                }
            }
        },
        "/equipment/{id}": {
            "get": {
                "description": "Возвращает информацию об оборудовании",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Получить оборудование по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID оборудования",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/equipment.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/equipment.EquipmentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Оборудование не найдено",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет данные оборудования",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Обновить оборудование",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID оборудования",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/equipment.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/equipment.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/equipment.EquipmentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    },
                    "404": {
                        "description": "Оборудование не найдено",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет оборудование по ID",
                "tags": [
                    "equipment"
                ],
                "summary": "Удалить оборудование",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID оборудования",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешное удаление"
                    },
                    "404": {
                        "description": "Оборудование не найдено",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    }
                }
            }
        },
        "/measuring-instruments": {
            "get": {
                "description": "Возвращает список средств измерения с пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Получить список средств измерения",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Количество записей на странице",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/measuringinstrument.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/measuringinstrument.MeasuringInstrumentResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/measuringinstrument.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/measuringinstrument.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новое средство измерения (СИ)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Создать средство измерения",
                "parameters": [
                    {
                        "description": "Данные средства измерения",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/measuringinstrument.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Средство измерения создано",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/measuringinstrument.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/measuringinstrument.MeasuringInstrumentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/measuringinstrument.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/measuringinstrument.Response"
                        }
                    }
                }
            }
        },
        "/measuring-instruments/{id}": {
            "get": {
                "description": "Возвращает информацию о средстве измерения",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Получить средство измерения по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID средства измерения",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/measuringinstrument.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/measuringinstrument.MeasuringInstrumentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Средство измерения не найдено",
                        "schema": {
                            "$ref": "#/definitions/measuringinstrument.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/measuringinstrument.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет данные средства измерения",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Обновить средство измерения",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID средства измерения",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/measuringinstrument.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/measuringinstrument.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/measuringinstrument.MeasuringInstrumentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/measuringinstrument.Response"
                        }
                    },
                    "404": {
                        "description": "Средство измерения не найдено",
                        "schema": {
                            "$ref": "#/definitions/measuringinstrument.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/measuringinstrument.Response"
                        }
                    }
                }
            }
        },
        "/organizations": {
            "get": {
                "description": "Возвращает список организаций с пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Получить список организаций",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Количество записей на странице",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/organization.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/organization.OrganizationResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/organization.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новую организацию (заказчика или подрядчика)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Создать организацию",
                "parameters": [
                    {
                        "description": "Данные организации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/organization.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Организация создана",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/organization.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/organization.OrganizationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    }
                }
            }
        },
        "/organizations/{id}": {
            "get": {
                "description": "Возвращает информацию об организации",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Получить организацию по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID организации",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/organization.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/organization.OrganizationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Организация не найдена",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет данные организации",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Обновить организацию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID организации",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/organization.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/organization.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/organization.OrganizationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    },
                    "404": {
                        "description": "Организация не найдена",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет организацию по ID",
                "tags": [
                    "organizations"
                ],
                "summary": "Удалить организацию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID организации",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешное удаление"
                    },
                    "404": {
                        "description": "Организация не найдена",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    }
                }
            }
        },
        "/standards": {
            "get": {
                "description": "Возвращает список эталонов с пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Получить список эталонов",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Количество записей на странице",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/standard.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/standard.StandardResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/standard.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/standard.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новый эталон для метрологической поверки",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Создать эталон",
                "parameters": [
                    {
                        "description": "Данные эталона",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/standard.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Эталон создан",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/standard.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/standard.StandardResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/standard.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/standard.Response"
                        }
                    }
                }
            }
        },
        "/standards/{id}": {
            "get": {
                "description": "Возвращает информацию об эталоне",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Получить эталон по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID эталона",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/standard.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/standard.StandardResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Эталон не найден",
                        "schema": {
                            "$ref": "#/definitions/standard.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/standard.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет данные эталона",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Обновить эталон",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID эталона",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/standard.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/standard.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/standard.StandardResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/standard.Response"
                        }
                    },
                    "404": {
                        "description": "Эталон не найден",
                        "schema": {
                            "$ref": "#/definitions/standard.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/standard.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет эталон по ID",
                "tags": [
                    "equipment"
                ],
                "summary": "Удалить эталон",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID эталона",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешное удаление"
                    },
                    "404": {
                        "description": "Эталон не найден",
                        "schema": {
                            "$ref": "#/definitions/standard.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/standard.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "agreement.AgreementResponse": {
            "type": "object",
            "properties": {
                "endDate": {
                    "type": "string"
                },
                "factoryId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "organizationId": {
                    "type": "string"
                },
                "scheduleId": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "subjectOfAgreement": {
                    "type": "string"
                }
            }
        },
        "agreement.CreateRequest": {
            "type": "object",
            "required": [
                "endDate",
                "factoryId",
                "number",
                "organizationId",
                "scheduleId",
                "source",
                "startDate",
                "subjectOfAgreement"
            ],
            "properties": {
                "endDate": {
                    "description": "формат \"2006-01-02\"",
                    "type": "string"
                },
                "factoryId": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "organizationId": {
                    "type": "string"
                },
                "scheduleId": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "startDate": {
                    "description": "формат \"2006-01-02\"",
                    "type": "string"
                },
                "subjectOfAgreement": {
                    "type": "string"
                }
            }
        },
        "agreement.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "agreement.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/agreement.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "agreement.UpdateRequest": {
            "type": "object",
            "properties": {
                "endDate": {
                    "type": "string"
                },
                "factoryId": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "organizationId": {
                    "type": "string"
                },
                "scheduleId": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "subjectOfAgreement": {
                    "type": "string"
                }
            }
        },
        "equipment.CreateRequest": {
            "type": "object",
            "required": [
                "equipmentDictionaryId",
                "factoryNumber",
                "manufactureYear",
                "organizationId",
                "statusId"
            ],
            "properties": {
                "equipmentDictionaryId": {
                    "type": "string"
                },
                "factoryNumber": {
                    "type": "string",
                    "maxLength": 50
                },
                "inventoryNumber": {
                    "type": "string"
                },
                "manufactureYear": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "registrationYear": {
                    "type": "string"
                },
                "statusId": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1
                }
            }
        },
        "equipment.EquipmentResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "equipmentDictionaryId": {
                    "type": "string"
                },
                "factoryNumber": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inventoryNumber": {
                    "type": "string"
                },
                "manufactureYear": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "registrationYear": {
                    "type": "string"
                },
                "statusId": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "equipment.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "equipment.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/equipment.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "equipment.UpdateRequest": {
            "type": "object",
            "properties": {
                "equipmentDictionaryId": {
                    "type": "string"
                },
                "factoryNumber": {
                    "type": "string"
                },
                "inventoryNumber": {
                    "type": "string"
                },
                "manufactureYear": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "registrationYear": {
                    "type": "string"
                },
                "statusId": {
                    "type": "integer"
                }
            }
        },
        "measuringinstrument.CreateRequest": {
            "type": "object",
            "required": [
                "certificateNumber",
                "documentProviderOrganization",
                "documentUrl",
                "metrologicalOperationTypeId",
                "organizationId",
                "registryNumber"
            ],
            "properties": {
                "certificateNumber": {
                    "type": "string",
                    "maxLength": 100
                },
                "documentProviderOrganization": {
                    "type": "string",
                    "maxLength": 100
                },
                "documentUrl": {
                    "type": "string",
                    "maxLength": 255
                },
                "lastOperationDate": {
                    "type": "string"
                },
                "metrologicalOperationTypeId": {
                    "type": "string"
                },
                "nextOperationDate": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "registryNumber": {
                    "type": "string",
                    "maxLength": 50
                },
                "standardId": {
                    "type": "string"
                }
            }
        },
        "measuringinstrument.MeasuringInstrumentResponse": {
            "type": "object",
            "properties": {
                "certificateNumber": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "documentProviderOrganization": {
                    "type": "string"
                },
                "documentUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastOperationDate": {
                    "type": "string"
                },
                "metrologicalOperationTypeId": {
                    "type": "string"
                },
                "nextOperationDate": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "registryNumber": {
                    "type": "string"
                },
                "standardId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "measuringinstrument.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "measuringinstrument.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/measuringinstrument.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "measuringinstrument.UpdateRequest": {
            "type": "object",
            "properties": {
                "certificateNumber": {
                    "type": "string"
                },
                "documentProviderOrganization": {
                    "type": "string"
                },
                "documentUrl": {
                    "type": "string"
                },
                "lastOperationDate": {
                    "type": "string"
                },
                "metrologicalOperationTypeId": {
                    "type": "string"
                },
                "nextOperationDate": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "registryNumber": {
                    "type": "string"
                },
                "standardId": {
                    "type": "string"
                }
            }
        },
        "organization.CreateRequest": {
            "type": "object",
            "required": [
                "address",
                "directorId",
                "inn",
                "kpp",
                "name",
                "propertyTypeId",
                "roleId"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "maxLength": 100
                },
                "directorId": {
                    "type": "string"
                },
                "inn": {
                    "type": "string"
                },
                "kpp": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 200
                },
                "parentId": {
                    "type": "string"
                },
                "poaExpirationDate": {
                    "type": "string"
                },
                "poaissueDate": {
                    "type": "string"
                },
                "powerOfAttorneyNumber": {
                    "type": "string"
                },
                "propertyTypeId": {
                    "type": "string"
                },
                "roleId": {
                    "type": "string"
                },
                "shortName": {
                    "type": "string"
                }
            }
        },
        "organization.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "organization.OrganizationResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "directorId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inn": {
                    "type": "string"
                },
                "kpp": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parentId": {
                    "type": "string"
                },
                "poaExpirationDate": {
                    "type": "string"
                },
                "poaIssueDate": {
                    "type": "string"
                },
                "powerOfAttorneyNumber": {
                    "type": "string"
                },
                "propertyTypeId": {
                    "type": "string"
                },
                "roleId": {
                    "type": "string"
                },
                "shortName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "organization.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/organization.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "organization.UpdateRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "directorId": {
                    "type": "string"
                },
                "inn": {
                    "type": "string"
                },
                "kpp": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parentId": {
                    "type": "string"
                },
                "poaExpirationDate": {
                    "type": "string"
                },
                "poaIssueDate": {
                    "type": "string"
                },
                "powerOfAttorneyNumber": {
                    "type": "string"
                },
                "propertyTypeId": {
                    "type": "string"
                },
                "roleId": {
                    "type": "string"
                },
                "shortName": {
                    "type": "string"
                }
            }
        },
        "standard.CreateRequest": {
            "type": "object",
            "required": [
                "certificateNumber",
                "documentProviderOrganization",
                "documentUrl",
                "metrologicalCharacteristics",
                "model"
            ],
            "properties": {
                "certificateNumber": {
                    "type": "string",
                    "maxLength": 100
                },
                "documentProviderOrganization": {
                    "type": "string",
                    "maxLength": 100
                },
                "documentUrl": {
                    "type": "string",
                    "maxLength": 255
                },
                "lastOperationDate": {
                    "type": "string"
                },
                "metrologicalCharacteristics": {
                    "type": "string"
                },
                "model": {
                    "type": "string",
                    "maxLength": 50
                },
                "nextOperationDate": {
                    "type": "string"
                }
            }
        },
        "standard.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "standard.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/standard.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "standard.StandardResponse": {
            "type": "object",
            "properties": {
                "certificateNumber": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "documentProviderOrganization": {
                    "type": "string"
                },
                "documentUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastOperationDate": {
                    "type": "string"
                },
                "metrologicalCharacteristics": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "nextOperationDate": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "standard.UpdateRequest": {
            "type": "object",
            "properties": {
                "certificateNumber": {
                    "type": "string"
                },
                "documentProviderOrganization": {
                    "type": "string"
                },
                "documentUrl": {
                    "type": "string"
                },
                "lastOperationDate": {
                    "type": "string"
                },
                "metrologicalCharacteristics": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "nextOperationDate": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "VRK API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
