// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agreements": {
            "get": {
                "description": "Возвращает список договоров с пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agreements"
                ],
                "summary": "Получить список договоров",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Количество записей на странице",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/agreement.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/agreement.AgreementResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/agreement.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новый договор между заказчиком и подрядчиком",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agreements"
                ],
                "summary": "Создать договор",
                "parameters": [
                    {
                        "description": "Данные договора",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/agreement.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Договор создан",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/agreement.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/agreement.AgreementResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    }
                }
            }
        },
        "/agreements/{id}": {
            "get": {
                "description": "Возвращает информацию о договоре",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agreements"
                ],
                "summary": "Получить договор по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID договора",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/agreement.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/agreement.AgreementResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Договор не найден",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет данные существующего договора",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agreements"
                ],
                "summary": "Обновить договор",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID договора",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/agreement.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/agreement.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/agreement.AgreementResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    },
                    "404": {
                        "description": "Договор не найден",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет договор по ID",
                "tags": [
                    "agreements"
                ],
                "summary": "Удалить договор",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID договора",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешное удаление"
                    },
                    "404": {
                        "description": "Договор не найден",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/agreement.Response"
                        }
                    }
                }
            }
        },
        "/equipment": {
            "get": {
                "description": "Возвращает список оборудования с пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Получить список оборудования",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Количество записей на странице",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/equipment.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/equipment.EquipmentResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/equipment.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новую единицу оборудования",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Создать оборудование",
                "parameters": [
                    {
                        "description": "Данные оборудования",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/equipment.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Оборудование создано",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/equipment.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/equipment.EquipmentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    }
                }
            }
        },
        "/equipment-dictionaries": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Получить список словарей оборудования",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Количество записей",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/equipmentdictionary.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/equipmentdictionary.EquipmentDictionaryFull"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/equipmentdictionary.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Создаёт equipment_dictionary, при необходимости создаёт measuring_instruments_dictionary и стандарты",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Создать словарь оборудования",
                "parameters": [
                    {
                        "description": "Данные",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/equipmentdictionary.CreateEquipmentDictionaryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/equipmentdictionary.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/equipmentdictionary.EquipmentDictionaryFull"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/equipmentdictionary.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/equipmentdictionary.ApiResponse"
                        }
                    }
                }
            }
        },
        "/equipment-dictionaries/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Получить словарь оборудования по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/equipmentdictionary.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/equipmentdictionary.EquipmentDictionaryFull"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/equipmentdictionary.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "equipment"
                ],
                "summary": "Удалить словарь оборудования",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/equipmentdictionary.ApiResponse"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Обновить словарь оборудования",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/equipmentdictionary.UpdateEquipmentDictionaryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/equipmentdictionary.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/equipmentdictionary.EquipmentDictionaryFull"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/equipmentdictionary.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/equipmentdictionary.ApiResponse"
                        }
                    }
                }
            }
        },
        "/equipment/{id}": {
            "get": {
                "description": "Возвращает информацию об оборудовании",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Получить оборудование по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID оборудования",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/equipment.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/equipment.EquipmentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Оборудование не найдено",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет оборудование по ID",
                "tags": [
                    "equipment"
                ],
                "summary": "Удалить оборудование",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID оборудования",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешное удаление"
                    },
                    "404": {
                        "description": "Оборудование не найдено",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    }
                }
            },
            "patch": {
                "description": "Обновляет данные оборудования",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Обновить оборудование",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID оборудования",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/equipment.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/equipment.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/equipment.EquipmentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    },
                    "404": {
                        "description": "Оборудование не найдено",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/equipment.Response"
                        }
                    }
                }
            }
        },
        "/manufacturers": {
            "get": {
                "description": "Возвращает список производителей с пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Получить список производителей",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Количество записей на странице",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/manufacturer.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/manufacturer.ManufacturerResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/manufacturer.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/manufacturer.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает нового производителя оборудования",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Создать производителя",
                "parameters": [
                    {
                        "description": "Данные производителя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/manufacturer.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Производитель создан",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/manufacturer.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/manufacturer.ManufacturerResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/manufacturer.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/manufacturer.Response"
                        }
                    }
                }
            }
        },
        "/manufacturers/{id}": {
            "get": {
                "description": "Возвращает информацию о производителе",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Получить производителя по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID производителя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/manufacturer.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/manufacturer.ManufacturerResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Производитель не найден",
                        "schema": {
                            "$ref": "#/definitions/manufacturer.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/manufacturer.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет производителя по ID",
                "tags": [
                    "equipment"
                ],
                "summary": "Удалить производителя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID производителя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешное удаление"
                    },
                    "404": {
                        "description": "Производитель не найден",
                        "schema": {
                            "$ref": "#/definitions/manufacturer.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/manufacturer.Response"
                        }
                    }
                }
            },
            "patch": {
                "description": "Обновляет данные производителя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Обновить производителя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID производителя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/manufacturer.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/manufacturer.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/manufacturer.ManufacturerResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/manufacturer.Response"
                        }
                    },
                    "404": {
                        "description": "Производитель не найден",
                        "schema": {
                            "$ref": "#/definitions/manufacturer.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/manufacturer.Response"
                        }
                    }
                }
            }
        },
        "/metrological-types": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Получить список типов метрологических операций",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Количество записей на странице",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/metrologicaltype.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/metrologicaltype.MetrologicalTypeResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/metrologicaltype.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Создать тип метрологической операции",
                "parameters": [
                    {
                        "description": "Данные типа",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/metrologicaltype.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/metrologicaltype.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/metrologicaltype.MetrologicalTypeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/metrologicaltype.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/metrologicaltype.Response"
                        }
                    }
                }
            }
        },
        "/metrological-types/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Получить тип метрологической операции по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID типа",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/metrologicaltype.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/metrologicaltype.MetrologicalTypeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/metrologicaltype.Response"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "equipment"
                ],
                "summary": "Удалить тип метрологической операции",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID типа",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/metrologicaltype.Response"
                        }
                    }
                }
            }
        },
        "/organizations": {
            "get": {
                "description": "Возвращает список организаций с пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Получить список организаций",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Количество записей на странице",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/organization.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/organization.OrganizationResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/organization.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новую организацию (заказчика или подрядчика)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Создать организацию",
                "parameters": [
                    {
                        "description": "Данные организации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/organization.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Организация создана",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/organization.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/organization.OrganizationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    }
                }
            }
        },
        "/organizations/{id}": {
            "get": {
                "description": "Возвращает информацию об организации",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Получить организацию по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID организации",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/organization.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/organization.OrganizationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Организация не найдена",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет данные организации",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Обновить организацию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID организации",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/organization.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/organization.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/organization.OrganizationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    },
                    "404": {
                        "description": "Организация не найдена",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет организацию по ID",
                "tags": [
                    "organizations"
                ],
                "summary": "Удалить организацию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID организации",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешное удаление"
                    },
                    "404": {
                        "description": "Организация не найдена",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/organization.Response"
                        }
                    }
                }
            }
        },
        "/usage-classifications": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Получить список классификаций использования",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Количество записей на странице",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Смещение",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/usageclassification.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/usageclassification.UsageClassificationResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/usageclassification.Meta"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Создать классификацию использования",
                "parameters": [
                    {
                        "description": "Данные классификации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usageclassification.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/usageclassification.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/usageclassification.UsageClassificationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/usageclassification.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/usageclassification.Response"
                        }
                    }
                }
            }
        },
        "/usage-classifications/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment"
                ],
                "summary": "Получить классификацию использования по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID классификации",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/usageclassification.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/usageclassification.UsageClassificationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/usageclassification.Response"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "equipment"
                ],
                "summary": "Удалить классификацию использования",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID классификации",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/usageclassification.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "agreement.AgreementResponse": {
            "type": "object",
            "properties": {
                "endDate": {
                    "type": "string"
                },
                "factoryId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "organizationId": {
                    "type": "string"
                },
                "scheduleId": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "subjectOfAgreement": {
                    "type": "string"
                }
            }
        },
        "agreement.CreateRequest": {
            "type": "object",
            "required": [
                "endDate",
                "factoryId",
                "number",
                "organizationId",
                "scheduleId",
                "source",
                "startDate",
                "subjectOfAgreement"
            ],
            "properties": {
                "endDate": {
                    "description": "формат \"2006-01-02\"",
                    "type": "string"
                },
                "factoryId": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "organizationId": {
                    "type": "string"
                },
                "scheduleId": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "startDate": {
                    "description": "формат \"2006-01-02\"",
                    "type": "string"
                },
                "subjectOfAgreement": {
                    "type": "string"
                }
            }
        },
        "agreement.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "agreement.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/agreement.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "agreement.UpdateRequest": {
            "type": "object",
            "properties": {
                "endDate": {
                    "type": "string"
                },
                "factoryId": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "organizationId": {
                    "type": "string"
                },
                "scheduleId": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "subjectOfAgreement": {
                    "type": "string"
                }
            }
        },
        "equipment.CreateRequest": {
            "type": "object",
            "required": [
                "equipmentDictionaryId",
                "factoryNumber",
                "manufactureYear",
                "manufacturerId",
                "organizationId",
                "statusId"
            ],
            "properties": {
                "certificateNumber": {
                    "type": "string"
                },
                "documentProviderOrganization": {
                    "type": "string"
                },
                "documentUrl": {
                    "type": "string"
                },
                "equipmentDictionaryId": {
                    "type": "string"
                },
                "factoryNumber": {
                    "type": "string",
                    "maxLength": 50
                },
                "inventoryNumber": {
                    "type": "string"
                },
                "lastOperationDate": {
                    "type": "string"
                },
                "manufactureYear": {
                    "type": "string"
                },
                "manufacturerId": {
                    "type": "string"
                },
                "metrologicalOperationTypeId": {
                    "description": "Для средств измерения",
                    "type": "integer"
                },
                "nextOperationDate": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "standardId": {
                    "type": "string"
                },
                "standards": {
                    "description": "Для эталонов",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/equipment.StandardCreateRequest"
                    }
                },
                "statusId": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1
                }
            }
        },
        "equipment.EquipmentResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "equipmentName": {
                    "type": "string"
                },
                "factoryNumber": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inventoryNumber": {
                    "type": "string"
                },
                "manufactureYear": {
                    "type": "string"
                },
                "manufacturerName": {
                    "type": "string"
                },
                "measuringInstrument": {
                    "$ref": "#/definitions/equipment.MeasuringInstrumentInfo"
                },
                "model": {
                    "type": "string"
                },
                "organizationName": {
                    "type": "string"
                },
                "standards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/equipment.StandardInfo"
                    }
                },
                "statusId": {
                    "type": "integer"
                },
                "statusName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "usageClassification": {
                    "type": "string"
                }
            }
        },
        "equipment.MeasuringInstrumentInfo": {
            "type": "object",
            "properties": {
                "certificateNumber": {
                    "type": "string"
                },
                "documentProviderOrganization": {
                    "type": "string"
                },
                "documentUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastOperationDate": {
                    "type": "string"
                },
                "metrologicalOperationType": {
                    "type": "string"
                },
                "metrologicalOperationTypeId": {
                    "type": "integer"
                },
                "nextOperationDate": {
                    "type": "string"
                },
                "registryNumber": {
                    "type": "string"
                },
                "standardId": {
                    "type": "string"
                }
            }
        },
        "equipment.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "equipment.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/equipment.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "equipment.StandardCreateRequest": {
            "type": "object",
            "required": [
                "model"
            ],
            "properties": {
                "certificateNumber": {
                    "type": "string"
                },
                "documentProviderOrganization": {
                    "type": "string"
                },
                "documentUrl": {
                    "type": "string"
                },
                "lastOperationDate": {
                    "type": "string"
                },
                "metrologicalCharacteristics": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "nextOperationDate": {
                    "type": "string"
                }
            }
        },
        "equipment.StandardInfo": {
            "type": "object",
            "properties": {
                "certificateNumber": {
                    "type": "string"
                },
                "documentProviderOrganization": {
                    "type": "string"
                },
                "documentUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastOperationDate": {
                    "type": "string"
                },
                "metrologicalCharacteristics": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "nextOperationDate": {
                    "type": "string"
                }
            }
        },
        "equipment.StandardUpdateRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "certificateNumber": {
                    "type": "string"
                },
                "documentProviderOrganization": {
                    "type": "string"
                },
                "documentUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastOperationDate": {
                    "type": "string"
                },
                "metrologicalCharacteristics": {
                    "type": "string"
                },
                "nextOperationDate": {
                    "type": "string"
                }
            }
        },
        "equipment.UpdateRequest": {
            "type": "object",
            "properties": {
                "certificateNumber": {
                    "type": "string"
                },
                "documentProviderOrganization": {
                    "type": "string"
                },
                "documentUrl": {
                    "type": "string"
                },
                "equipmentDictionaryId": {
                    "type": "string"
                },
                "factoryNumber": {
                    "description": "Основные поля оборудования",
                    "type": "string"
                },
                "inventoryNumber": {
                    "type": "string"
                },
                "lastOperationDate": {
                    "type": "string"
                },
                "manufactureYear": {
                    "type": "string"
                },
                "manufacturerId": {
                    "type": "string"
                },
                "metrologicalOperationTypeId": {
                    "description": "Поля средства измерения",
                    "type": "integer"
                },
                "nextOperationDate": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "standards": {
                    "description": "Эталоны",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/equipment.StandardUpdateRequest"
                    }
                },
                "statusId": {
                    "type": "integer"
                }
            }
        },
        "equipmentdictionary.ApiResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/equipmentdictionary.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "equipmentdictionary.CreateEquipmentDictionaryRequest": {
            "type": "object",
            "properties": {
                "fullName": {
                    "type": "string"
                },
                "measuringInstrument": {
                    "$ref": "#/definitions/equipmentdictionary.MeasuringInstrumentInput"
                },
                "model": {
                    "type": "string"
                }
            }
        },
        "equipmentdictionary.EquipmentDictionaryFull": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mid": {
                    "$ref": "#/definitions/equipmentdictionary.MeasuringInstrumentsDictionaryFull"
                },
                "model": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "equipmentdictionary.MeasuringInstrumentInput": {
            "type": "object",
            "properties": {
                "metrologicalOperationTypeId": {
                    "type": "integer"
                },
                "registryNumber": {
                    "type": "string"
                },
                "standards": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "standardModel"
                    ]
                }
            }
        },
        "equipmentdictionary.MeasuringInstrumentUpdateInput": {
            "type": "object",
            "properties": {
                "metrologicalOperationTypeId": {
                    "type": "integer"
                },
                "registryNumber": {
                    "type": "string"
                },
                "standards": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "standardModel"
                    ]
                }
            }
        },
        "equipmentdictionary.MeasuringInstrumentsDictionaryFull": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "metrologicalOperationType": {
                    "type": "string"
                },
                "metrologicalOperationTypeID": {
                    "type": "integer",
                    "format": "int32"
                },
                "registryNumber": {
                    "type": "string"
                },
                "standards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/equipmentdictionary.StandardsDictionaryFull"
                    }
                }
            }
        },
        "equipmentdictionary.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "equipmentdictionary.StandardsDictionaryFull": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                }
            }
        },
        "equipmentdictionary.UpdateEquipmentDictionaryRequest": {
            "type": "object",
            "properties": {
                "fullName": {
                    "type": "string"
                },
                "measuringInstrument": {
                    "$ref": "#/definitions/equipmentdictionary.MeasuringInstrumentUpdateInput"
                },
                "model": {
                    "type": "string"
                }
            }
        },
        "manufacturer.CreateRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "classificationID": {
                    "type": "integer",
                    "format": "int32"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "manufacturer.ManufacturerResponse": {
            "type": "object",
            "properties": {
                "classificationID": {
                    "type": "integer",
                    "format": "int32"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "manufacturer.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "manufacturer.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/manufacturer.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "manufacturer.UpdateRequest": {
            "type": "object",
            "properties": {
                "classificationID": {
                    "type": "integer",
                    "format": "int32"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "metrologicaltype.CreateRequest": {
            "type": "object",
            "required": [
                "metrologicalOperationType"
            ],
            "properties": {
                "metrologicalOperationType": {
                    "type": "string"
                }
            }
        },
        "metrologicaltype.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "metrologicaltype.MetrologicalTypeResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "metrologicalOperationType": {
                    "type": "string"
                }
            }
        },
        "metrologicaltype.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/metrologicaltype.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "organization.CreateRequest": {
            "type": "object",
            "required": [
                "address",
                "directorId",
                "inn",
                "kpp",
                "name",
                "propertyTypeId",
                "roleId"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "maxLength": 100
                },
                "directorId": {
                    "type": "string"
                },
                "inn": {
                    "type": "string"
                },
                "kpp": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 200
                },
                "parentId": {
                    "type": "string"
                },
                "poaExpirationDate": {
                    "type": "string"
                },
                "poaissueDate": {
                    "type": "string"
                },
                "powerOfAttorneyNumber": {
                    "type": "string"
                },
                "propertyTypeId": {
                    "type": "string"
                },
                "roleId": {
                    "type": "string"
                },
                "shortName": {
                    "type": "string"
                }
            }
        },
        "organization.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "organization.OrganizationResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "directorName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inn": {
                    "type": "string"
                },
                "kpp": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parentId": {
                    "type": "string"
                },
                "poaExpirationDate": {
                    "type": "string"
                },
                "poaIssueDate": {
                    "type": "string"
                },
                "powerOfAttorneyNumber": {
                    "type": "string"
                },
                "propertyType": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "shortName": {
                    "type": "string"
                }
            }
        },
        "organization.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/organization.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "organization.UpdateRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "directorId": {
                    "type": "string"
                },
                "inn": {
                    "type": "string"
                },
                "kpp": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parentId": {
                    "type": "string"
                },
                "poaExpirationDate": {
                    "type": "string"
                },
                "poaIssueDate": {
                    "type": "string"
                },
                "powerOfAttorneyNumber": {
                    "type": "string"
                },
                "propertyTypeId": {
                    "type": "string"
                },
                "roleId": {
                    "type": "string"
                },
                "shortName": {
                    "type": "string"
                }
            }
        },
        "usageclassification.CreateRequest": {
            "type": "object",
            "required": [
                "classification"
            ],
            "properties": {
                "classification": {
                    "type": "string"
                }
            }
        },
        "usageclassification.Meta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "usageclassification.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/usageclassification.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "usageclassification.UsageClassificationResponse": {
            "type": "object",
            "properties": {
                "classification": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "VRK API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
