package bootstrap

import "errors"

var (
	ErrOrganizationNameRequired   = errors.New("organization name is required")
	ErrFirstAdminNameRequired     = errors.New("first admin name is required")
	ErrEmployeeNameRequired       = errors.New("employee name is required")
	ErrEmailRequired              = errors.New("email is required")
	ErrInvalidEmail               = errors.New("email must be valid")
	ErrInvalidOrganizationRole    = errors.New("organization role is invalid")
	ErrInviteRoleTemplateRequired = errors.New("invite role template is required")
	ErrInviteRoleTemplateInvalid  = errors.New("invite role template is invalid")
	ErrInviteRoleScopeInvalid     = errors.New("invite role template is not compatible with scope type")
	ErrInviteScopeTypeInvalid     = errors.New("invite scope type must be organization, division, or unit")
	ErrInviteScopeTargetRequired  = errors.New("invite scope target is required")
	ErrInviteScopeTargetInvalid   = errors.New("invite scope target is invalid")
	ErrInviteExpiryRequired       = errors.New("invite expiry is required")
	ErrInviteExpiryInvalid        = errors.New("invite expiry must be in the future")
	ErrPasswordTooShort           = errors.New("password must be at least 8 characters")
	ErrInvalidCredentials         = errors.New("invalid email or password")
	ErrInviteNotFound             = errors.New("invite not found")
	ErrInviteExpired              = errors.New("invite expired")
	ErrInviteAlreadyAccepted      = errors.New("invite already accepted")
	ErrInviteRevoked              = errors.New("invite revoked")
	ErrInviteDraftRequired        = errors.New("invite must stay in draft before sending")
	ErrInviteSendNotAllowed       = errors.New("invite cannot be sent in its current state")
	ErrInviteRevokeNotAllowed     = errors.New("invite cannot be revoked in its current state")
	ErrUnauthorized               = errors.New("unauthorized")
	ErrForbidden                  = errors.New("forbidden")
	ErrAccessSelectionRequired    = errors.New("multiple eligible access paths found; explicit workspace selection is required")
	ErrLaunchAlreadyCompleted     = errors.New("launch wizard already completed")
	ErrLaunchRequired             = errors.New("organization must be active before this action")
	ErrStructureModeInvalid       = errors.New("structure mode must be division or unit")
	ErrPropertyTypeRequired       = errors.New("property type is required")
	ErrPropertyTypeInvalid        = errors.New("property type must be ООО, АО, or ПАО")
	ErrInnRequired                = errors.New("inn is required")
	ErrKppRequired                = errors.New("kpp is required")
	ErrLegalAddressRequired       = errors.New("legal address is required")
	ErrContactPhoneRequired       = errors.New("contact phone is required")
	ErrDivisionNameRequired       = errors.New("division name is required")
	ErrDivisionTypeRequired       = errors.New("division type is required")
	ErrUnitNameRequired           = errors.New("unit name is required")
	ErrUnitTypeRequired           = errors.New("unit type is required")
	ErrInvalidID                  = errors.New("invalid id")
	ErrStructureTypeInvalid       = errors.New("unit type must be ВРД, ВРЗ, ВУ, or ВРП")
	ErrDivisionNotFound           = errors.New("division not found")
	ErrUnitNotFound               = errors.New("unit not found")
	ErrArchiveBlocked             = errors.New("archive blocked by active references")
	ErrDivisionTargetInvalid      = errors.New("division target is invalid")
)
