package agreement

import "errors"

var (
	ErrUnauthorized                   = errors.New("unauthorized")
	ErrForbidden                      = errors.New("forbidden")
	ErrInvalidID                      = errors.New("invalid agreement ID")
	ErrNotFound                       = errors.New("agreement not found")
	ErrConflict                       = errors.New("agreement was changed by another request, retry the update")
	ErrCreateFailed                   = errors.New("failed to create agreement")
	ErrUpdateFailed                   = errors.New("failed to update agreement")
	ErrListFailed                     = errors.New("failed to list agreements")
	ErrCheckExistsFailed              = errors.New("failed to check agreement existence")
	ErrInvalidUUID                    = errors.New("invalid UUID format")
	ErrInvalidDate                    = errors.New("invalid date format, expected YYYY-MM-DD")
	ErrInvalidDateRange               = errors.New("end date must be after start date")
	ErrContractorOrganizationRequired = errors.New("contractor organization is required")
	ErrContractorOrganizationInvalid  = errors.New("contractor organization is invalid")
	ErrContractNumberRequired         = errors.New("contract number is required")
	ErrContractStatusRequired         = errors.New("contract status is required")
	ErrContractStatusInvalid          = errors.New("contract status is invalid")
	ErrWorkTypeRequired               = errors.New("work type is required")
	ErrWorkTypeInvalid                = errors.New("work type is invalid")
	ErrEquipmentTypeRequired          = errors.New("equipment type is required")
	ErrRegionRequired                 = errors.New("region is required")
	ErrScopeConflict                  = errors.New("division and unit scope cannot be set together")
	ErrScopeInvalid                   = errors.New("contract scope is invalid")
	ErrRoutingUnitRequired            = errors.New("routing unit is required")
	ErrRoutingUnitInvalid             = errors.New("routing unit is invalid")
	ErrRoutingWorkTypeRequired        = errors.New("routing work type is required")
	ErrRoutingEquipmentTypeRequired   = errors.New("routing equipment type is required")
	ErrRoutingRegionRequired          = errors.New("routing region is required")
)
