package measuringinstrument

import "errors"

var (
	ErrUnauthorized               = errors.New("unauthorized")
	ErrForbidden                  = errors.New("forbidden")
	ErrInvalidID                  = errors.New("invalid measuring instrument ID")
	ErrNotFound                   = errors.New("measuring instrument not found")
	ErrNameRequired               = errors.New("name is required")
	ErrTypeRequired               = errors.New("instrument type is required")
	ErrModelRequired              = errors.New("model is required")
	ErrRegistrationNumberRequired = errors.New("registration number is required")
	ErrSerialNumberRequired       = errors.New("serial number is required")
	ErrUnitRequired               = errors.New("unit is required")
	ErrPlacementKindRequired      = errors.New("placement kind is required")
	ErrPlacementKindInvalid       = errors.New("placement kind is invalid")
	ErrEquipmentRequired          = errors.New("equipment is required for built-in instruments")
	ErrEquipmentInvalid           = errors.New("equipment is invalid for current scope")
	ErrStandardInvalid            = errors.New("one or more standards are invalid")
	ErrOperationTypeRequired      = errors.New("operation type is required")
	ErrOperationTypeInvalid       = errors.New("operation type is invalid")
	ErrOperationDateRequired      = errors.New("operation date is required")
	ErrOperationDateInvalid       = errors.New("operation date is invalid")
	ErrDocumentNumberRequired     = errors.New("document number is required")
	ErrExecutorRequired           = errors.New("executor organization is required")
	ErrValidUntilInvalid          = errors.New("valid until is invalid")
	ErrArchivedTarget             = errors.New("archived measuring instruments cannot be changed")
	ErrAlreadyArchived            = errors.New("measuring instrument is already archived")
	ErrCreateFailed               = errors.New("failed to create measuring instrument")
	ErrUpdateFailed               = errors.New("failed to update measuring instrument")
	ErrListFailed                 = errors.New("failed to list measuring instruments")
	ErrArchiveFailed              = errors.New("failed to archive measuring instrument")
)
