import type {
  ContractRecord,
  ContractorOption,
  EmployeeAccessResponse,
  EmployeeInviteResponse,
  EquipmentRecord,
  JournalRecord,
  MeasuringInstrumentRecord,
  PublicInviteInspectionResponse,
  SessionSummaryResponse,
  StandardRecord,
} from "@/shared/api";

export function cloneFixture<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

export const runtimeSession: SessionSummaryResponse = {
  sessionToken: "storybook-session-customer-admin",
  requiresLaunchWizard: false,
  membershipId: "membership-customer-admin",
  membershipStatus: "active",
  account: {
    id: "account-admin",
    fullName: "Анна Волкова",
    email: "a.volkova@vrk.local",
  },
  organization: {
    id: "org-customer",
    roleTitle: "customer",
    type: "ООО",
    propertyType: "ООО",
    name: "ВРК Север",
    shortName: "ВРК Север",
    inn: "7801000000",
    kpp: "780101001",
    legalAddress: "197000, Санкт-Петербург, Петровская наб., 4",
    registeredAddress: "197000, Санкт-Петербург, Петровская наб., 4",
    contactEmail: "office@vrk.local",
    contactPhone: "+7 812 000-00-00",
    leaderFullName: "Анна Волкова",
    leaderPosition: "Директор",
    contractPhone: "+7 812 000-00-10",
    contractEmail: "contracts@vrk.local",
    actingBasis: "Устав",
    launchState: "active",
  },
  grant: {
    id: "grant-organization-admin",
    roleTemplate: "organization_admin",
    scopeType: "organization",
    scopeId: "org-customer",
  },
  workspace: {
    scopeType: "organization",
    scopeId: "org-customer",
    scopeName: "Вся организация",
    landingTitle: "Компания",
    landingSubtitle: "Управление реквизитами, структурой и доступом сотрудников.",
    landingPath: "/company",
    canManageEmployeeInvites: true,
    canViewEmployees: true,
    canManageEmployees: true,
  },
  divisions: [
    {
      id: "division-north",
      type: "Филиал",
      name: "Северный филиал",
      code: "NORTH",
      region: "Санкт-Петербург",
      registeredAddress: "197000, Санкт-Петербург, Петровская наб., 4",
      managerName: "Илья Романов",
      leaderFullName: "Илья Романов",
      leaderPosition: "Руководитель филиала",
      contractPhone: "+7 812 000-01-00",
      contractEmail: "north@vrk.local",
      actingBasis: "Доверенность",
      status: "active",
      comment: "Основная площадка заказчика.",
    },
    {
      id: "division-east",
      type: "Филиал",
      name: "Восточный филиал",
      code: "EAST",
      region: "Ленинградская область",
      registeredAddress: "188000, Ленинградская область, промзона Восточная",
      managerName: "Мария Кузнецова",
      leaderFullName: "Мария Кузнецова",
      leaderPosition: "Руководитель филиала",
      contractPhone: "+7 812 000-02-00",
      contractEmail: "east@vrk.local",
      actingBasis: "Доверенность",
      status: "active",
    },
  ],
  units: [
    {
      id: "unit-boiler",
      type: "ВРД",
      name: "Котельный участок",
      code: "BOILER",
      region: "Санкт-Петербург",
      divisionId: "division-north",
      registeredAddress: "197000, Санкт-Петербург, корпус 2",
      managerName: "Павел Орлов",
      leaderFullName: "Павел Орлов",
      leaderPosition: "Начальник участка",
      contractPhone: "+7 812 000-11-00",
      contractEmail: "boiler@vrk.local",
      actingBasis: "Приказ",
      status: "active",
    },
    {
      id: "unit-metrology",
      type: "ВУ",
      name: "Метрологическая лаборатория",
      code: "METRO",
      region: "Санкт-Петербург",
      divisionId: "division-north",
      registeredAddress: "197000, Санкт-Петербург, корпус 5",
      managerName: "Сергей Лебедев",
      leaderFullName: "Сергей Лебедев",
      leaderPosition: "Главный метролог",
      contractPhone: "+7 812 000-12-00",
      contractEmail: "metrology@vrk.local",
      actingBasis: "Приказ",
      status: "active",
    },
    {
      id: "unit-depot",
      type: "ВРЗ",
      name: "Ремонтное депо",
      code: "DEPOT",
      region: "Ленинградская область",
      divisionId: "division-east",
      registeredAddress: "188000, Ленинградская область, корпус 1",
      managerName: "Николай Егоров",
      leaderFullName: "Николай Егоров",
      leaderPosition: "Начальник депо",
      contractPhone: "+7 812 000-21-00",
      contractEmail: "depot@vrk.local",
      actingBasis: "Приказ",
      status: "active",
    },
  ],
};

export const emptyStructureSession: SessionSummaryResponse = {
  ...cloneFixture(runtimeSession),
  divisions: [],
  units: [],
  workspace: {
    ...runtimeSession.workspace,
    landingSubtitle: "Добавьте первое подразделение или юнит.",
  },
};

export const divisionScopeSession: SessionSummaryResponse = {
  ...cloneFixture(runtimeSession),
  sessionToken: "storybook-session-division",
  membershipId: "membership-division",
  account: {
    id: "account-division",
    fullName: "Илья Романов",
    email: "i.romanov@vrk.local",
  },
  grant: {
    id: "grant-division-operator",
    roleTemplate: "division_operator",
    scopeType: "division",
    scopeId: "division-north",
  },
  workspace: {
    scopeType: "division",
    scopeId: "division-north",
    scopeName: "Северный филиал",
    landingTitle: "Северный филиал",
    landingSubtitle: "Доступ ограничен своим подразделением и его юнитами.",
    landingPath: "/company",
    canManageEmployeeInvites: false,
    canViewEmployees: false,
    canManageEmployees: false,
  },
  divisions: cloneFixture(runtimeSession.divisions.filter((item) => item.id === "division-north")),
  units: cloneFixture(runtimeSession.units.filter((item) => item.divisionId === "division-north")),
};

export const contractorSession: SessionSummaryResponse = {
  ...cloneFixture(runtimeSession),
  sessionToken: "storybook-session-contractor",
  membershipId: "membership-contractor",
  account: {
    id: "account-contractor",
    fullName: "Виктор Смирнов",
    email: "v.smirnov@service.local",
  },
  organization: {
    ...runtimeSession.organization,
    id: "org-contractor",
    roleTitle: "contractor",
    name: "ТехСервис Метролоджик",
    shortName: "ТСМ",
    inn: "7802000000",
    kpp: "780201001",
  },
  grant: {
    id: "grant-contractor",
    roleTemplate: "organization_admin",
    scopeType: "organization",
    scopeId: "org-contractor",
  },
  workspace: {
    scopeType: "organization",
    scopeId: "org-contractor",
    scopeName: "ТехСервис Метролоджик",
    landingTitle: "Договоры подрядчика",
    landingSubtitle: "Договоры заказчиков, доступные вашей организации.",
    landingPath: "/contracts",
    canManageEmployeeInvites: false,
    canViewEmployees: false,
    canManageEmployees: false,
  },
  divisions: [],
  units: [],
};

export const restrictedCustomerSession: SessionSummaryResponse = {
  ...cloneFixture(runtimeSession),
  sessionToken: "storybook-session-auditor",
  account: {
    id: "account-auditor",
    fullName: "Олег Сафонов",
    email: "o.safonov@vrk.local",
  },
  grant: {
    id: "grant-auditor",
    roleTemplate: "auditor",
    scopeType: "organization",
    scopeId: "org-customer",
  },
  workspace: {
    ...runtimeSession.workspace,
    scopeName: "Аудиторский доступ",
    landingSubtitle: "Просмотр без изменения данных.",
    canManageEmployeeInvites: false,
    canViewEmployees: true,
    canManageEmployees: false,
  },
};

export const organizationHeadSession: SessionSummaryResponse = {
  ...cloneFixture(runtimeSession),
  sessionToken: "storybook-session-organization-head",
  membershipId: "membership-organization-head",
  account: {
    id: "account-organization-head",
    fullName: "Дмитрий Ковалев",
    email: "d.kovalev@vrk.local",
  },
  grant: {
    id: "grant-organization-head",
    roleTemplate: "organization_head",
    scopeType: "organization",
    scopeId: "org-customer",
  },
  workspace: {
    ...runtimeSession.workspace,
    scopeName: "Вся организация",
    landingSubtitle: "Просмотр организации и сотрудников без изменения доступа.",
    canManageEmployeeInvites: false,
    canViewEmployees: true,
    canManageEmployees: false,
  },
};

export const divisionHeadSession: SessionSummaryResponse = {
  ...cloneFixture(divisionScopeSession),
  sessionToken: "storybook-session-division-head",
  membershipId: "membership-division-head",
  account: {
    id: "account-division-head",
    fullName: "Илья Романов",
    email: "i.romanov@vrk.local",
  },
  grant: {
    id: "grant-division-head",
    roleTemplate: "division_head",
    scopeType: "division",
    scopeId: "division-north",
  },
  workspace: {
    ...divisionScopeSession.workspace,
    canViewEmployees: true,
    canManageEmployees: false,
  },
};

export const unitHeadSession: SessionSummaryResponse = {
  ...cloneFixture(runtimeSession),
  sessionToken: "storybook-session-unit-head",
  membershipId: "membership-unit-head",
  account: {
    id: "account-unit-head",
    fullName: "Сергей Лебедев",
    email: "s.lebedev@vrk.local",
  },
  grant: {
    id: "grant-unit-head",
    roleTemplate: "unit_head",
    scopeType: "unit",
    scopeId: "unit-metrology",
  },
  workspace: {
    scopeType: "unit",
    scopeId: "unit-metrology",
    scopeName: "Метрологическая лаборатория",
    landingTitle: "Метрологическая лаборатория",
    landingSubtitle: "Доступ ограничен выбранным юнитом.",
    landingPath: "/company",
    canManageEmployeeInvites: false,
    canViewEmployees: true,
    canManageEmployees: false,
  },
  divisions: [],
  units: cloneFixture(runtimeSession.units.filter((item) => item.id === "unit-metrology")),
};

export const firstAdminInvite: PublicInviteInspectionResponse = {
  inviteKind: "first_admin",
  organizationId: runtimeSession.organization.id,
  organizationName: runtimeSession.organization.name,
  organizationRole: "customer",
  inviteStatus: "sent",
  inviteeName: "Анна Волкова",
  inviteEmail: "a.volkova@vrk.local",
  inviteExpiresAt: "2026-05-06T09:00:00.000Z",
  launchState: "active",
};

export const employeeInviteInspection: PublicInviteInspectionResponse = {
  inviteKind: "employee",
  organizationId: runtimeSession.organization.id,
  organizationName: runtimeSession.organization.name,
  organizationRole: "customer",
  inviteStatus: "sent",
  inviteeName: "Илья Романов",
  inviteEmail: "i.romanov@vrk.local",
  inviteExpiresAt: "2026-05-06T09:00:00.000Z",
  roleTemplate: "division_operator",
  scopeType: "division",
  scopeLabel: "Северный филиал",
  launchState: "active",
};

export const employeeInvites: EmployeeInviteResponse[] = [
  {
    id: "invite-001",
    fullName: "Мария Кузнецова",
    email: "m.kuznetsova@vrk.local",
    roleTemplate: "division_head",
    scopeType: "division",
    scopeId: "division-east",
    scopeLabel: "Восточный филиал",
    status: "sent",
    inviteToken: "employee-east",
    acceptPath: "/register/employee-east",
    expiresAt: "2026-05-06T12:00:00.000Z",
    sentAt: "2026-04-29T09:00:00.000Z",
  },
  {
    id: "invite-002",
    fullName: "Сергей Лебедев",
    email: "s.lebedev@vrk.local",
    roleTemplate: "unit_head",
    scopeType: "unit",
    scopeId: "unit-metrology",
    scopeLabel: "Метрологическая лаборатория",
    status: "accepted",
    inviteToken: "employee-metrology",
    acceptPath: "/register/employee-metrology",
    expiresAt: "2026-05-03T12:00:00.000Z",
    sentAt: "2026-04-25T09:00:00.000Z",
    openedAt: "2026-04-25T10:30:00.000Z",
    acceptedAt: "2026-04-25T10:42:00.000Z",
  },
  {
    id: "invite-003",
    fullName: "Олег Сафонов",
    email: "o.safonov@vrk.local",
    roleTemplate: "auditor",
    scopeType: "organization",
    scopeId: runtimeSession.organization.id,
    scopeLabel: runtimeSession.organization.name,
    status: "draft",
    expiresAt: "2026-05-10T12:00:00.000Z",
  },
];

export const employeeAccessRows: EmployeeAccessResponse[] = [
  {
    accessId: "grant-organization-admin",
    membershipId: "membership-customer-admin",
    accountId: "account-admin",
    fullName: "Анна Волкова",
    email: "a.volkova@vrk.local",
    roleTemplate: "organization_admin",
    scopeType: "organization",
    scopeId: runtimeSession.organization.id,
    scopeLabel: runtimeSession.organization.name,
    membershipStatus: "active",
  },
  {
    accessId: "grant-organization-head",
    membershipId: "membership-organization-head",
    accountId: "account-organization-head",
    fullName: "Дмитрий Ковалев",
    email: "d.kovalev@vrk.local",
    roleTemplate: "organization_head",
    scopeType: "organization",
    scopeId: runtimeSession.organization.id,
    scopeLabel: runtimeSession.organization.name,
    membershipStatus: "active",
  },
  {
    accessId: "grant-division-head",
    membershipId: "membership-division-head",
    accountId: "account-division-head",
    fullName: "Илья Романов",
    email: "i.romanov@vrk.local",
    roleTemplate: "division_head",
    scopeType: "division",
    scopeId: "division-north",
    scopeLabel: "Северный филиал",
    membershipStatus: "active",
  },
  {
    accessId: "grant-unit-head",
    membershipId: "membership-unit-head",
    accountId: "account-unit-head",
    fullName: "Сергей Лебедев",
    email: "s.lebedev@vrk.local",
    roleTemplate: "unit_head",
    scopeType: "unit",
    scopeId: "unit-metrology",
    scopeLabel: "Метрологическая лаборатория",
    membershipStatus: "active",
  },
  {
    accessId: "grant-division-operator-east",
    membershipId: "membership-division-operator-east",
    accountId: "account-division-operator-east",
    fullName: "Мария Кузнецова",
    email: "m.kuznetsova@vrk.local",
    roleTemplate: "division_operator",
    scopeType: "division",
    scopeId: "division-east",
    scopeLabel: "Восточный филиал",
    membershipStatus: "active",
  },
  {
    accessId: "grant-auditor",
    membershipId: "membership-auditor",
    accountId: "account-auditor",
    fullName: "Олег Сафонов",
    email: "o.safonov@vrk.local",
    roleTemplate: "auditor",
    scopeType: "organization",
    scopeId: runtimeSession.organization.id,
    scopeLabel: runtimeSession.organization.name,
    membershipStatus: "active",
  },
];

export const contractorOptions: ContractorOption[] = [
  { id: "org-contractor", name: "ТехСервис Метролоджик", shortName: "ТСМ" },
  { id: "org-remline", name: "РемЛиния-24" },
];

export const contractRecords: ContractRecord[] = [
  {
    id: "contract-001",
    customerOrganizationId: runtimeSession.organization.id,
    customerOrganizationName: runtimeSession.organization.name,
    contractorOrganizationId: "org-contractor",
    contractorOrganizationName: "ТехСервис Метролоджик",
    contractNumber: "Договор №14/24-М",
    contractStatus: "active",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    workType: "verification",
    equipmentType: "расходомер",
    region: "Санкт-Петербург",
    locationScope: {
      scopeType: "unit",
      scopeId: "unit-metrology",
      label: "Метрологическая лаборатория",
    },
    subjectOfAgreement: "Поверка и калибровка средств измерения",
    routingEligible: true,
  },
  {
    id: "contract-002",
    customerOrganizationId: runtimeSession.organization.id,
    customerOrganizationName: runtimeSession.organization.name,
    contractorOrganizationId: "org-remline",
    contractorOrganizationName: "РемЛиния-24",
    contractNumber: "Рамочный договор №91-ТО",
    contractStatus: "inactive",
    startDate: "2026-02-01",
    endDate: "2027-01-31",
    workType: "maintenance",
    equipmentType: "компрессор",
    region: "Ленинградская область",
    locationScope: {
      scopeType: "division",
      scopeId: "division-east",
      label: "Восточный филиал",
    },
    subjectOfAgreement: "Техническое обслуживание оборудования депо",
    routingEligible: false,
  },
];

export const equipmentRecords: EquipmentRecord[] = [
  {
    id: "equipment-001",
    organizationId: runtimeSession.organization.id,
    unit: {
      id: "unit-boiler",
      name: "Котельный участок",
      divisionId: "division-north",
      divisionName: "Северный филиал",
    },
    manufacturer: "ПромТепло",
    classification: "Котельное оборудование",
    model: "PT-400",
    fullName: "Паровой котел PT-400",
    factoryNumber: "PT400-7781",
    inventoryNumber: "EQ-1001",
    manufactureYear: 2022,
    status: "active",
    comment: "Основной агрегат участка.",
    documentUrl: "https://example.local/equipment/pt-400.pdf",
    measuringInstrumentCount: 1,
    createdAt: "2026-01-15T09:00:00.000Z",
    updatedAt: "2026-04-20T09:00:00.000Z",
  },
  {
    id: "equipment-002",
    organizationId: runtimeSession.organization.id,
    unit: {
      id: "unit-depot",
      name: "Ремонтное депо",
      divisionId: "division-east",
      divisionName: "Восточный филиал",
    },
    manufacturer: "КомпрессорСервис",
    classification: "Компрессор",
    model: "KS-12",
    fullName: "Компрессорная станция KS-12",
    factoryNumber: "KS12-4420",
    inventoryNumber: "EQ-2040",
    manufactureYear: 2020,
    status: "inactive",
    measuringInstrumentCount: 0,
    archivedAt: "2026-04-18T09:00:00.000Z",
    createdAt: "2026-01-20T09:00:00.000Z",
    updatedAt: "2026-04-18T09:00:00.000Z",
  },
];

export const journalRecords: JournalRecord[] = [
  {
    id: "journal-001",
    operationType: "verification",
    operationDate: "2026-04-20",
    documentNumber: "СВ-2026-041",
    validUntil: "2027-04-20",
    executorOrganization: "ТехСервис Метролоджик",
    attachmentUrl: "https://example.local/journals/sv-2026-041.pdf",
    comment: "Поверка выполнена без замечаний.",
    createdAt: "2026-04-20T11:00:00.000Z",
  },
  {
    id: "journal-002",
    operationType: "calibration",
    operationDate: "2026-03-12",
    documentNumber: "КЛ-2026-018",
    validUntil: "2027-03-12",
    executorOrganization: "ТехСервис Метролоджик",
    createdAt: "2026-03-12T11:00:00.000Z",
  },
];

export const standardRecords: StandardRecord[] = [
  {
    id: "standard-001",
    organizationId: runtimeSession.organization.id,
    ownershipScope: {
      scopeType: "division",
      scopeId: "division-north",
      label: "Северный филиал",
    },
    standardType: "Эталон давления",
    model: "ED-25",
    identifier: "STD-ED-25",
    serialNumber: "ED25-144",
    metrologicalCharacteristics: "0-25 МПа, класс 0.05",
    status: "active",
    documentUrl: "https://example.local/standards/ed-25.pdf",
    linkedMeasuringInstruments: 1,
    journalCount: 1,
    nextDueDate: "2027-03-12",
    latestJournal: journalRecords[1],
    createdAt: "2026-01-25T09:00:00.000Z",
    updatedAt: "2026-03-12T11:00:00.000Z",
  },
  {
    id: "standard-002",
    organizationId: runtimeSession.organization.id,
    ownershipScope: {
      scopeType: "unit",
      scopeId: "unit-metrology",
      label: "Метрологическая лаборатория",
    },
    standardType: "Эталон расхода",
    model: "ER-10",
    identifier: "STD-ER-10",
    serialNumber: "ER10-552",
    metrologicalCharacteristics: "0-10 м3/ч, класс 0.1",
    status: "retired",
    linkedMeasuringInstruments: 0,
    journalCount: 0,
    archivedAt: "2026-04-10T09:00:00.000Z",
    createdAt: "2026-01-28T09:00:00.000Z",
    updatedAt: "2026-04-10T09:00:00.000Z",
  },
];

export const measuringInstrumentRecords: MeasuringInstrumentRecord[] = [
  {
    id: "mi-001",
    organizationId: runtimeSession.organization.id,
    unit: {
      id: "unit-metrology",
      name: "Метрологическая лаборатория",
      divisionId: "division-north",
      divisionName: "Северный филиал",
    },
    equipment: {
      id: "equipment-001",
      fullName: "Паровой котел PT-400",
    },
    name: "Расходомер линии подготовки",
    instrumentType: "Расходомер",
    model: "RM-80",
    registrationNumber: "SI-2026-019",
    serialNumber: "RM80-8120",
    status: "active",
    placementKind: "built_in",
    standards: [
      {
        id: "standard-001",
        standardType: "Эталон давления",
        model: "ED-25",
        identifier: "STD-ED-25",
        serialNumber: "ED25-144",
        status: "active",
        scopeLabel: "Северный филиал",
      },
    ],
    journalCount: 1,
    nextDueDate: "2027-04-20",
    latestJournal: journalRecords[0],
    createdAt: "2026-02-02T09:00:00.000Z",
    updatedAt: "2026-04-20T11:00:00.000Z",
  },
  {
    id: "mi-002",
    organizationId: runtimeSession.organization.id,
    unit: {
      id: "unit-metrology",
      name: "Метрологическая лаборатория",
      divisionId: "division-north",
      divisionName: "Северный филиал",
    },
    name: "Манометр контрольный",
    instrumentType: "Манометр",
    model: "MK-160",
    registrationNumber: "SI-2026-024",
    serialNumber: "MK160-450",
    status: "inactive",
    placementKind: "standalone",
    standards: [],
    journalCount: 0,
    archivedAt: "2026-04-12T09:00:00.000Z",
    createdAt: "2026-02-10T09:00:00.000Z",
    updatedAt: "2026-04-12T09:00:00.000Z",
  },
];
