package equipment

import "errors"

var (
	ErrManufacturerRequired               = errors.New("manufacturer_id is required")
	ErrOrganizationRequired               = errors.New("organization_id is required")
	ErrFactoryNumberRequired              = errors.New("factory_number is required")
	ErrManufactureYearRequired            = errors.New("manufacture_year is required")
	ErrStatusRequired                     = errors.New("status_id is required")
	ErrEquipmentDictionaryRequired        = errors.New("equipment_dictionary_id is required")
	ErrInvalidUUID                        = errors.New("invalid UUID format")
	ErrInvalidID                          = errors.New("invalid equipment ID")
	ErrNotFound                           = errors.New("equipment not found")
	ErrCreateFailed                       = errors.New("failed to create equipment")
	ErrUpdateFailed                       = errors.New("failed to update equipment")
	ErrDeleteFailed                       = errors.New("failed to delete equipment")
	ErrListFailed                         = errors.New("failed to list equipment")
	ErrCheckExistsFailed                  = errors.New("failed to check equipment existence")
	ErrInvalidDateFormat                  = errors.New("invalid date format, expected YYYY-MM-DD")
	ErrManufacturerNotFound               = errors.New("manufacturer not found")
	ErrEquipmentDictNotFound              = errors.New("equipment dictionary not found")
	ErrOrganizationNotFound               = errors.New("organization not found")
	ErrStatusNotFound                     = errors.New("equipment status not found")
	ErrFactoryNumberTooLong               = errors.New("factory number must not exceed 50 characters")
	ErrInventoryNumberTooLong             = errors.New("inventory number must not exceed 50 characters")
	ErrMetrologicalTypeNotFound           = errors.New("metrological operation type not found")
	ErrCertificateNumberTooLong           = errors.New("certificate number must not exceed 100 characters")
	ErrDocProviderTooLong                 = errors.New("document provider organization must not exceed 200 characters")
	ErrDocumentURLTooLong                 = errors.New("document URL must not exceed 255 characters")
	ErrStandardModelNotFound              = errors.New("standard model not found in dictionary")
	ErrStandardCertNumberTooLong          = errors.New("standard certificate number must not exceed 100 characters")
	ErrStandardDocProviderTooLong         = errors.New("standard document provider must not exceed 100 characters")
	ErrStandardDocumentURLTooLong         = errors.New("standard document URL must not exceed 255 characters")
	ErrMetrologicalCharacteristicsTooLong = errors.New("metrological characteristics too long")
)
